version: '3'
services:
  pix:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    environment:
      - REDIS_HOST=redis
      - CELERY_BROKER=redis://redis:6379/0
      - VECTOR_DB_HOST=vector_db
    depends_on:
      - redis
      - vector_db
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  vector_db:
    # Specify the image and configuration for your vector database
    image: your-vector-db-image:latest
    ports:
      - 5432:5432

